---
  - name: Ansible archive Examples
    hosts: all
    tasks:
      - name: Getting timestamp
        shell: date +'%Y%m%d%'
        register: timestamp_raw
        
      - name: Wait for 2 minutes
        pause:
          seconds: 120
          
      - name: Wait for 2 minutes
        pause:
          seconds: 120

      - name: Wait for 3 minutes
        pause:
          seconds: 180
