---
- name: Download and extract JMeter
  get_url:
    url: "https://mirror.olnevhost.net/pub/apache/jmeter/binaries/apache-jmeter-5.4.1.tgz"
    dest: "/home/hz/jmeter"
  become: yes
- name: Extract JMeter archive
  unarchive:
    src: "/home/hz/jmeter/apache-jmeter-5"
