---
- name: Ansible archive Examples
  hosts: all
  tasks:
  - name: Getting timestamp
    shell: date +'%Y%m%d%'
    register: timestamp_raw

  - name: Getting name for backup
    set_fact: timestamp={{ timestamp_raw.stdout }}

  - name: Compress Directory contents
    become: yes
    archive:
       path: /usr/test
       dest: /usr/backup_{{ timestamp }}.tar  
       format: tar
